### ISSUE TITLE
where to get build pre-requistes

### ISSUE THREAD

**Issue by lee-martin** [trento-project/trento#216]
Two points I encountered on build pre-requistes:

1)
https://github.com/trento-project/trento/blob/main/README.md#L80-L81

```
- [`Go`](https://golang.org/) ^1.16
```

Regarding the required Go compiler, on SLES the Development tools module needs activating, e.g. "SLE-Module-DevTools15-SP3-Updates".   On opensuse Leap Go is available, so fine there.

2)

```
- [`Node.js`](https://nodejs.org/es/) ^15.x
```

I can't find nodejs15 on standard Leap or SLES repositories, so we should document where SUSE users should get this from. Maybe https://software.opensuse.org/package/nodejs15 ?

thanks, lee

**Comment by stefanotorresi** [comment]
Actually, we just need to fix the `https://nodejs.org/es/` link to `https://nodejs.org`.

Whoever wants to build the thing from source might not even want to use the package manager, or they might not be using any SUSE distribution.

Users are invited to look up to the upstream project documentation on how to install them in their environment; we don't want to get into the rabbit hole of writing documentation about that (because it has been done already by upstream, for example: https://nodejs.org/en/download/package-manager/#opensuse-and-sle).

**Comment by stefanotorresi** [comment]
Made invalid by container builds. All build dependencies are now provided there.
