### ISSUE TITLE
No information on the SAP System is offered in the SAP Systems view

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#485]
http://demo.trento-project.io/sapsystems

At moment we don't have Health information at page SAP Systems.

**Comment by abravosuse** [comment]
My two cents on this: I can see the value of having a health section in the SAP systems view similar to the one we have in the Hosts view or the Pacemaker Cluster view. But we have to be careful when we give a SAP system a green status. Trento is designed to collect information at OS level but a SAP system lives in other layers as well (e.g. the application or the database layer). A SAP system may have all its instances in green status (based in sapcontrol RCs) but being inoperable due to a syntax error in the ABAP code.

**Comment by stefanotorresi** [comment]
> A SAP system may have all its instances in green status (based in sapcontrol RCs) but being inoperable due to a syntax error in the ABAP code.

I can definitely say that this level of insights is out-of-scope at the moment.

If SAPControl tells us it's green, then we tell the user it's green. 🙂

**Comment by abravosuse** [comment]
> > A SAP system may have all its instances in green status (based in sapcontrol RCs) but being inoperable due to a syntax error in the ABAP code.
> 
> I can definitely say that this level of insights is out-of-scope at the moment.
> 
> If SAPControl tells us it's green, then we tell the user it's green. 🙂

And that's perfectly fine. We just need to ensure that it is somewhere well documented that a SAP system in green status means that all its instances are in green status.

**Comment by abravosuse** [comment]
I see this as a potential enhancement but not necessarily something to be addressed right now. I've registered the suggestion under https://confluence.suse.com/display/SAP/Collection+point+for+potential+Trento+enhancements. The issue can be closed for now.

**Comment by fabriziosestito** [comment]
Closing as for the comment above
