### ISSUE TITLE
Status of SAP instance doesn't get updated after trento-agent got stopped 

### ISSUE THREAD

**Issue by Zaoliang** [trento-project/trento#491]
I stopped trento-agent on vmnwprd04 and vmnwprd04 disappered from Hosts list which is another issue in general.
The status should get updated and but it keeps 'SAPControl-GREEN'.

See http://13.95.71.67/sapsystems/97a1e70aeff3c0685d65c4c3d32d533b

**Comment by abravosuse** [comment]
A little bit of background on this: we wanted to see how Trento reacts when the Trento agent running in a host with a PAS or AAS SAP instance crashes. For that we stopped the agent running in the AAS host (vmnwprd04) and then checked the status in Trento Console. We checked two things:

1. The status of the AAS instance (#02) in the SAP system detail view: we expected it to be unknown (given that the agent is stopped) but instead it was showing green. It might be that Trento is retrieving the status information using SSH. In which case, there is nothing to say.
2. The status of host vmnwprd04 itself: we expected the host to be in critical status with Agent status = stopped. But instead we found host vmnwprd04 gone from the list of hosts. Maybe that's how it is supposed to work by design but, in my opinion, if Trento Server cannot connect to an agent, the corresponding host should still show in the list with Agent status = stopped, so that we can act on it.

**Comment by abravosuse** [comment]
@lee-martin no, we captured the problem in the tests (test ID 05.160) but now that I'm reviewing the script I notice that we used this issue as a reference rather than opening a new one. I will create one right away.

**Comment by abravosuse** [comment]
@lee-martin done issue #536

**Comment by arbulu89** [comment]
Hey @abravosuse ,
Here some comments:
1. This is tricky thing you ask hehe When the agent stops working, we simply stop getting data so we are not able to update the data coming from this node, and we show the latest stored information. In this case, the unique thing we could do is check if the agent is not running, and in this case, only update the `Status` column to `Unknown`, 
2. The host status is updated properly since the recent changes. Now, once the trento agent is stopped, the host will report an error icon in the host list and it has a error badge in the host specific view saying that the runner is not working:
![image](https://user-images.githubusercontent.com/36370954/146533915-12f6e101-8167-44d7-8b67-5d56bf9aae34.png)
![image](https://user-images.githubusercontent.com/36370954/146533947-fb05d9f9-6605-431f-bfc9-a2f76bba7d4f.png)

Finally, talking about states, there is work to do in the SAP system list page, as there, in the status icons, we always show a grey icon...

**Comment by abravosuse** [comment]
Hi @arbulu89 

1. Status `Unknown` is good because it's all that Trento can say about the instance at that moment.
2. That looks great. We will confirm in our 3rd testing round.

Thank you!

**Comment by abravosuse** [comment]
v0.7.0: 

1. Status still showing as SAPControl-Green rather than Unknown. Fix pending.
2. Trento Agent status showing as Not Running. Great!

**Comment by arbulu89** [comment]
@abravosuse As commented, the 1st point is a really tricky thing, and I think we shouldn't implement the 1st solution that comes to our mind. After thinking it twice, I wouldn't implement anything like `put Unknown` or similar.
We need to decide project wide but happens when the agents stops sending data. Maybe, we need to apply some generic strategy for this like:
- Remove data from not running agents
- Set some kind of flag if the data has not been updated because the agent is not running
- How to visualize this. Maybe we need to make the whole row like grayish, or some other visualization.

As commented, this needs some team work to think about this generic scenario

**Comment by stefanotorresi** [comment]
I totally agree with Xabi that we need a generalized solution for this problem, and this needs going to the drawing board and properly design it.

**Comment by abravosuse** [comment]
I also agree with @arbulu89. I will include it as a potential enhancement to be reviewed in the future: what to do, console wide, when an agent is not reachable. At least now we are not seeing instances in green status with an agent stopped. That's a big step further.

Issue can be closed.
