### ISSUE TITLE
SAP systems view: PAS instance (01) not listed under NWP

### ISSUE THREAD

**Issue by abravosuse** [trento-project/trento#609]
Environment: QA Testing Round #3.
Version: v0.7.0

In the SAP systems view, PAS instance (01) is not listed under system NWP:

![image](https://user-images.githubusercontent.com/91731013/146729974-df8ea1c3-a423-412d-bdfe-cf008b7129cd.png)

However, you can see it in the system detail view when you click on the system ID:

![image](https://user-images.githubusercontent.com/91731013/146730174-3dec9f94-fedb-4f53-9596-57cde6f2ef91.png)

And when you click on the corresponding host (vmnwprd03), you can also see it in the SAP instance section:

![image](https://user-images.githubusercontent.com/91731013/146730340-0c68d57b-bb6a-4701-b00f-7ad7492fe698.png)

**Comment by arbulu89** [comment]
Finally, I have been able to reproduce the issue and understand why it happens.
The error is in the pagination.
The pagination takes by default 10 entries (which by the way, we cannot manage with the pagination cursors in this particular page...).
But the items are not taken by systems, they are taken by instances, that's why we don't get more than 10 instances here.

I will work in a fix

**Comment by abravosuse** [comment]
v0.7.0+git.dev39.1640009634.6e57174: fixed. Issue can be closed.
