### ISSUE TITLE
DB address appears as `<nil>` in the demo environment

### ISSUE THREAD

**Issue by rtorrero** [trento-project/trento#704]
After upgrading the demo environment to the new azure subscription, I noticed that in the SAP systems view, we list SID `NWP` with DB address `<nil>`
![DB address NIL](https://user-images.githubusercontent.com/2668401/149504667-13807a35-fbe6-4177-9433-9b7ed760c964.png)

We are seeing similar issues in other deployments with sometimes the DB address appearing while others it doesn't show.

**Comment by arbulu89** [comment]
This issue is happening because the `SAPDBHOST` entry doesn't exist in the SAP profile file.
We use this parameter to know where the DB is, and create the relationship.

There are 2 possibilities here:
1. There is an issue in the SAP installation itself, and we cannot get the needed information to visualize the attached DB. In this case, the unique thing we could do is to display better that there is some issue in the installation
2. There is other way to get in the Netweaver site where the database is (some other file, some command, etc). This would require changes in the code.

@abravosuse How we could discard the option 1?

**Comment by arbulu89** [comment]
Apparently something went wrong in the installation. 
Adding the next values to the `DEFAULT.PFL` file fixes the issue.
```
SAPDBHOST = 10.90.1.13
dbms/type = hdb
dbms/name = HDQ
dbs/hdb/dbname = HDQ
```

But it opens a new. The old sap system entry is not removed, leaving 2 cloned entries in the SAP systems list.

**Comment by arbulu89** [comment]
I have tested in our demo environment, and the duplicated system thing doesn't happen.
This was actually fixed some days ago with: https://github.com/trento-project/trento/commit/a3a5118c49320d27e63ed16a3c50bea164ad0aad

**Comment by abravosuse** [comment]
@arbulu89 After adding the missing parameters in the DEFAULT profile of system NWQ, I could see duplicated entries in the SAP Systems view for that system. But today, the obsolete entry is gone and only the good one remains: Check http://20.126.33.235/sapsystems. I guess that after sometime Trento cleans up itself?

**Comment by arbulu89** [comment]
Hey @abravosuse ,
Honestly, I don't know how this could happen in your version, as it doesn't have any cleaning mechanism.
Anyway, I vote for closing this ticket as it has a fix already on place

**Comment by abravosuse** [comment]
Yes it can be closed. Unfortunately I don't have authorization to do it. Can you please take care of it? Thanks!
